name: 'smartwatch'
# version: 0.0.1, We're not publishing this, so not necessary?
description: A smartwatch application prototype using HTML, CSS & Dart/Javascript
authors:
- Benjamin Dutton
- Allan Tan
- Thomas Farr
homepage: https://github.com/NimbleNavigatorsCOSC/COSC345

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: any
  dart_to_js_script_rewriter: any

dev_dependencies:
  test: any

transformers:
- dart_to_js_script_rewriter
- test/pub_serve:
    $include:
    - test/**_test.dart